Models/Message.cs
using System.ComponentModel.DataAnnotations;

namespace la_mia_pizzeria_post.Models
{
    public class Message
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }

        public string Name { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        public Message()
        {

        }
    }
}

Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_post.Models
{
    public class Pizza
    {
        public Pizza(string nome, string descrizione, string image, decimal prezzo)
        {
            Nome = nome;
            Descrizione = descrizione;
            Image = image;
            Prezzo = prezzo;
        }

        public Pizza()
        {

        }

        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Il campo nome è obbligatorio")]
        [StringLength(30, ErrorMessage = "Il nome non può avere più di 30 caratteri")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Il campo descrizione è obbligatorio")]
        [StringLength(100, ErrorMessage = "La descrizione non può avere più di 100 caratteri")]
        [MoreWordValidation]
        public string Descrizione { get; set; }
        [Url(ErrorMessage = "Il campo immagine deve essere un Link")]
        [Required(ErrorMessage = "Il campo immagine è obbligatorio")]
        public string Image { get; set; }
        [Required(ErrorMessage = "Il campo prezzo è obbligatorio")]
        [Range(1, 99, ErrorMessage = "Il prezzo deve essere fra 1 e 99 Euro")]
        public decimal Prezzo { get; set; }

        public int? CategoryId { get; set; }   
        public Category? Category { get; set; }

        public List<Ingredient>? Ingredients { get; set; }
    }
}

Controllers/Api/MessageController.cs
using la_mia_pizzeria_post.Models;
using Microsoft.AspNetCore.Mvc;


namespace la_mia_pizzeria_post.Controllers.Api
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class MessageController : Controller
    {
        [HttpPost]
        public IActionResult Send([FromBody] Message  message)
        {
            Context context = new Context();
            context.Messages.Add(message);
            context.SaveChanges();
            return Ok();
        }
    }
}

Controllers/Api/PizzaController.cs
using la_mia_pizzeria_post.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using System.Data.Entity;

namespace la_mia_pizzeria_post.Controllers.Api
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class PizzaController : ControllerBase
    {
        Context _context;
        public PizzaController()
        {
            _context = new Context();
        }
        [HttpGet]
        public IActionResult Get(string? name)
        {
            IQueryable<Pizza> pizzas;
            if (name != null)
            {
                pizzas = _context.Pizza.Include("Category").Include("Ingredients").Where(pizza => pizza.Nome.ToLower().Contains(name.ToLower()));

            }
            else
            {
                pizzas = _context.Pizza.Include("Category").Include("Ingredients");
            }

            return Ok(pizzas.ToList<Pizza>());

        }

        [HttpGet("{id}")]
        public IActionResult Get(int id)
        {
            Pizza pizza = _context.Pizza.Where(piz => piz.Id == id).FirstOrDefault();
            return Ok(pizza);
        }


        [HttpPut("{id}")]
        public IActionResult Put(int id, [FromBody] Pizza model)
        {
            if (!ModelState.IsValid)
            {
                return UnprocessableEntity(ModelState);
            }
            
                
                Pizza pizzaSearch = _context.Pizza
                .Where(pizza => pizza.Id == id).FirstOrDefault();
                if (pizzaSearch != null)
                {
                    return Ok(pizzaSearch);
                }
                else
                {
                    return NotFound();
                }
            
        }

        [HttpDelete("{id}")]
        public IActionResult Delete(int id)
        {
            
            
                Pizza pizzaDelete = _context.Pizza
                .Where(pizza => pizza.Id == id).FirstOrDefault();
                if (pizzaDelete != null)
                {
                    _context.Pizza.Remove(pizzaDelete);
                    _context.SaveChanges();
                    return Ok();
                }
                else
                {
                    return NotFound();
                }
            
        }
    }
}

Controllers/PizzaController.cs
using la_mia_pizzeria_post.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Linq;

namespace la_mia_pizzeria_post.Controllers
{
    [Authorize]
    public class PizzaController : Controller
    {
        readonly Context _context = new();

        public IActionResult Index()
        {
            List<Pizza> pizzaList = _context.Pizza.Include("Category").Include("Ingredients").ToList();
            return View(pizzaList);
        }
        public IActionResult Details(int id)
        {       
            Pizza pizza = _context.Pizza.Where(Pizza=> Pizza.Id == id).Include("Category").Include("Ingredients").First();
            if (pizza == null)
            {
                return NotFound($"La Pizza con id {id} non è stato trovato");
            }
            else
            {
                return View("Details", pizza);
            }
        }

        public IActionResult Create()
        {
            CategoriesPizzas categoriesPizzas = new CategoriesPizzas();
            categoriesPizzas.Categories = new Context().Category.ToList();
            categoriesPizzas.Ingredients = new Context().Ingredient.ToList();
            
            return View(categoriesPizzas);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoriesPizzas form)
        {
            if (!ModelState.IsValid)
            {
                form.Categories = _context.Category.ToList();
                form.Ingredients = _context.Ingredient.ToList();
                return View("Create", form);
            }
            form.Pizza.Ingredients = _context.Ingredient.Where(ingredient => form.SelectedIngredients.Contains(ingredient.Id)).ToList<Ingredient>();

            Aggiungi(form.Pizza);
            return RedirectToAction("Index");
        }
        
        public IActionResult Update(int id)
        {

            Pizza pizza = _context.Pizza.Where(_ => _.Id == id).Include("Category").Include("Ingredients").First();
            CategoriesPizzas categoriesPizzas = new CategoriesPizzas();
            categoriesPizzas.Pizza = pizza;
            categoriesPizzas.Categories = _context.Category.ToList();
            categoriesPizzas.Ingredients = _context.Ingredient.ToList();

            return View(categoriesPizzas);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, CategoriesPizzas form)
        {
            if (!ModelState.IsValid)
            {
                form.Pizza.Id = id;
                form.Pizza.Ingredients = _context.Ingredient.Where(i => form.SelectedIngredients.Contains(i.Id)).ToList();
                form.Categories = _context.Category.ToList();
                form.Ingredients = _context.Ingredient.ToList();
                return View("Update", form);
            }
            Pizza pizza = _context.Pizza.Where(pizza => pizza.Id == id).Include("Ingredients").First();
            pizza.Nome = form.Pizza.Nome;
            pizza.Image = form.Pizza.Image;
            pizza.Descrizione = form.Pizza.Descrizione;
            pizza.CategoryId = form.Pizza.CategoryId;
            pizza.Ingredients = _context.Ingredient.Where(ingredient => form.SelectedIngredients.Contains(ingredient.Id)).ToList();


            _context.Pizza.Update(pizza);

            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {

            Pizza pizza = _context.Pizza.Where(_ => _.Id == id).Include("Category").Include("Ingredients").First();
            _context.Pizza.Remove(pizza);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
        public void Aggiungi(Pizza pizza)
        {
            _context.Add(pizza);
            _context.SaveChanges();
        }

        public IActionResult Messages()
        {
            List<Message> messageList = _context.Messages.ToList();
            return View(messageList);
        }

    }
}

Views/Pizza/Create.cshtml
@model CategoriesPizzas;

<form asp-controller="Pizza" asp-action="Create" method="post">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="Nome">Nome pizza</label>
        <input asp-for="Pizza.Nome" type="text" class="form-control"  placeholder="Nome pizza">
        <span asp-validation-for="Pizza.Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Descrizione">Descrizione pizza</label>
        <input asp-for="Pizza.Descrizione" type="text" class="form-control" placeholder="Descrizione pizza">
        <span asp-validation-for="Pizza.Descrizione" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Image">Immagine pizza</label>
        <input asp-for="Pizza.Image" type="text" class="form-control" placeholder="url immagine pizza">
        <span asp-validation-for="Pizza.Image" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Prezzo">Prezzo pizza</label>
        <input asp-for="Pizza.Prezzo" type="number" class="form-control" placeholder="Prezzo pizza">
        <span asp-validation-for="Pizza.Prezzo" class="text-danger"></span>
    </div>

    @*CATEGORIA*@
    <div class="my-3">
        <label for="CategoryId">Categoria pizza</label>
        <select asp-for="Pizza.CategoryId" rows="10" class="d-block w-100">

            @foreach (Category category in Model.Categories)
            {
                <option value="@category.Id">@category.Name</option>
            }
        </select>
        <span asp-validation-for="Pizza.CategoryId" class="text-danger"></span>
    </div>

    @*INGREDIENTI*@
    <div class="my-3">
        <label for="SelectedIngredients"></label>
        <select multiple="multiple" asp-for="SelectedIngredients" rows="10" class="d-block w-100">
            @foreach (Ingredient ingredient in Model.Ingredients)
            {
                <option value="@ingredient.Id">@ingredient.Name</option>
            }
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/Pizza/Details.cshtml
@model Pizza

<div class="card m-auto" style="width: 25%;">
    <img src="@Model.Image" />
    <div class="card-body">
        <h5 class="card-title">@Model.Nome</h5>
        <p class="card-text">@Model.Descrizione</p>
        <p class="card-text">@Model.Category.Name</p>
        <div class="d-flex justify-content-between">
            <a class="btn btn-primary" asp-area="" asp-controller="Pizza" asp-action="Index">Indietro</a>
            <a class="btn btn-secondary " href="@Url.Action("Update", "Pizza", new {Id= @Model.Id})">Modifica</a>
            <form asp-controller="Pizza" asp-action="Delete" asp-route-id="@Model.Id">
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    </div>
</div>

Views/Pizza/Index.cshtml
@model List<Pizza>

<a class="btn btn-primary" href="@Url.Action("Create")">Crea nuova pizza</a>
<a class="btn btn-primary mx-5" href="@Url.Action("Messages")">Messaggi</a>
<table class="table container">
    @if(Model.Count >0){
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Ingredienti</th>
                <th scope="col">Categoria</th>
                <th scope="col">Foto</th>
                <th scope="col">Prezzo</th>
            </tr>
        </thead>
        <tbody>     
            
            @foreach (Pizza pizza in Model)
            {
            
                <tr>
                    <td>@pizza.Id</td>
                    <td>@pizza.Nome</td>
                    <td>
                        @foreach(Ingredient ingredient in pizza.Ingredients){
                            <span><i>@ingredient.Name,</i> </span>
                        }
                    </td>
                    <td>@pizza.Category.Name</td>
                    <td><img src="@pizza.Image" /></td>
                    <td>@pizza.Prezzo &euro;</td>
                    <td><a class="btn btn-outline-primary" href="@Url.Action("Details", "Pizza", new {Id= pizza.Id})">Dettagli</a></td>
                    <td><a class="btn btn-outline-secondary " href="@Url.Action("Update", "Pizza", new {Id= pizza.Id})">Modifica</a></td>
                    <td>
                        <form asp-controller="Pizza" asp-action="Delete" asp-route-id="@pizza.Id">
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                        </form>
                    </td>
                </tr> 
            }

    </tbody>
    }
    else
    {
         <tr>
             <td><h2>Non ci sono pizze.</h2></td>
         </tr>
    }
</table>

Views/Pizza/Messages.cshtml
@model List<Message>

<a class="btn btn-primary" href="@Url.Action("Index")">Indietro</a>

<table class="table container">
    @if(Model.Count >0){
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Titolo</th>
                <th scope="col">Testo</th>
                <th scope="col">Email</th>
            </tr>
        </thead>
        <tbody>     
            
            @foreach (Message message in Model)
            {     
                <tr>
                    <td>@message.Id</td>
                    <td>@message.Name</td>
                    <td>@message.Title</td>
                    <td>@message.Text</td>
                    <td>@message.Email</td>            
                </tr> 
            }
    </tbody>
    }
    else
    {
         <tr>
             <td><h2>Non ci sono messaggi.</h2></td>
         </tr>
    }
</table>

Views/Pizza/Update.cshtml
@model CategoriesPizzas;

<form asp-controller="Pizza" asp-action="Update" method="post" asp-route-id="@Model.Pizza.Id">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="Nome">Nome pizza</label>
        <input asp-for="Pizza.Nome" type="text" class="form-control" placeholder="Nome pizza">
        <span asp-validation-for="Pizza.Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Descrizione">Descrizione pizza</label>
        <input asp-for="Pizza.Descrizione" type="text" class="form-control" placeholder="Descrizione pizza">
        <span asp-validation-for="Pizza.Descrizione" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Image">Immagine pizza</label>
        <input asp-for="Pizza.Image" type="text" class="form-control" placeholder="url immagine pizza">
        <span asp-validation-for="Pizza.Image" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Prezzo">Prezzo pizza</label>
        <input asp-for="Pizza.Prezzo" type="number" class="form-control" placeholder="Prezzo pizza">
        <span asp-validation-for="Pizza.Prezzo" class="text-danger"></span>
    </div>
    <div class="my-3">
        <label for="CategoryId">Categoria pizza</label>
        <select asp-for="Pizza.CategoryId" rows="10" class="d-block w-100">

            @foreach (Category category in Model.Categories)
            {
                @if (Model.Pizza.CategoryId == category.Id)
                {
                    <option value="@category.Id" selected>@category.Name</option>
                }
                else
                {
                    <option value="@category.Id">@category.Name</option>
                }
            }
        </select>
        <span asp-validation-for="Pizza.CategoryId" class="text-danger"></span>
    </div>

    @*INGREDIENTI*@
    <div class="my-3">
        <label for="SelectedIngredients"></label>
        <select multiple="multiple" asp-for="SelectedIngredients" rows="10" class="d-block w-100">
            @foreach (Ingredient ingredient in Model.Ingredients)
            {
                @if (Model.Pizza.Ingredients.Contains(ingredient))
                {
                    <option selected value="@ingredient.Id">@ingredient.Name</option>
                }
                else
                {

                    <option value="@ingredient.Id">@ingredient.Name</option>
                }
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>